name: leancode_kratos_client
description: >
  A Flutter library for connecting to Ory Kratos.
  It helps manage user authentication, registration, making it simple to add identity features to your app.

repository: https://github.com/leancodepl/leancode_kratos
version: 0.5.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  collection: ^1.19.1
  copy_with_extension: ^10.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.10.1
  copy_with_extension_gen: ^10.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  leancode_lint: ^19.0.0
  mocktail: ^1.0.4
